### ISSUE TITLE
NBTTagFloat and NBTTagDouble do not consider NaN in equality check

### ISSUE THREAD

**Issue by Marcono1234** [MrYurihi/TBNBT#2]
https://github.com/MrYurihi/TBNBT/blob/e298baaa7ef86ce7e0dfee4a709cfc35b521abef/src/main/java/com/github/mryurihi/tbnbt/tag/NBTTagFloat.java#L73
https://github.com/MrYurihi/TBNBT/blob/e298baaa7ef86ce7e0dfee4a709cfc35b521abef/src/main/java/com/github/mryurihi/tbnbt/tag/NBTTagDouble.java#L73

Both do not consider the case where the stored value is `NaN` and therefore the `==` check fails.
The correct implementation would be to use the following methods:
```java
private boolean equals(float a, float b) {
	// See Float.equals
	return Float.floatToIntBits(a) == Float.floatToIntBits(b);
}
```

```java
private boolean equals(double a, double b) {
	// See Double.equals
	return Double.doubleToLongBits(a) == Double.doubleToLongBits(b);
}
```

**Comment by MrYurihi** [comment]
Just looking through Minecraft's code, they use `==` so I am going to leave as is
